name: Meetfolio CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 서브 모듈 접근하기
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          submodules: true

      # 서브 모듈 변경 점 있으면 update
      - name: Git Sumbodule Update
        run: |
          git submodule update --remote --recursive

      # gradlew 권한 변경
      - name: Grant execute permission for gradlew
        run : chmod +x gradlew

      # Gradle Buuild (test 부분 제외)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build -x test

      # Docker
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/meetfolio:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/meetfolio:latest

      - name: Deploy in GCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/meetfolio:latest
            sudo docker tag ${{ secrets.DOCKER_USERNAME }}/meetfolio:latest meetfolio:latest
            sudo docker rm -f meetfolio-server
            sudo docker run -d --name meetfolio-server -e TZ=Asia/Seoul -p 9090:9090 meetfolio:latest
            docker image prune -af
